spring:
  application:
    name: coder-practice-backend
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coder_practice?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

server:
  port: 8001
  servlet:
    context-path: /api


mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除配置
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml

# springdoc-openapi配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.codebear.coderpracticebackend.controller
  api-docs:
    enabled: true
# knife4j配置
knife4j:
  enable: true
  setting:
    language: zh_cn
  openapi:
    title: 编程练习系统API文档
    description: "编程练习系统接口文档"
    email: admin@example.com
    concat: 管理员
    url: https://github.com
    version: v1.0
    license: Apache 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0
    terms-of-service-url: https://github.com



